// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Student_Management_System.Data;

#nullable disable

namespace Student_Management_System.Migrations
{
    [DbContext(typeof(AppDbcontext))]
    partial class AppDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.Property<int>("CoursesId")
                        .HasColumnType("int");

                    b.Property<int>("StudentsId")
                        .HasColumnType("int");

                    b.HasKey("CoursesId", "StudentsId");

                    b.HasIndex("StudentsId");

                    b.ToTable("CourseStudent");
                });

            modelBuilder.Entity("Student_Management_System.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Descriptoin");

                    b.Property<int>("DurationInHours")
                        .HasColumnType("int");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Introduction to C# programming",
                            DurationInHours = 40,
                            InstructorId = 1,
                            Name = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Introduction to databases and SQL",
                            DurationInHours = 35,
                            InstructorId = 2,
                            Name = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Arrays, linked lists, stacks, queues and trees",
                            DurationInHours = 45,
                            InstructorId = 1,
                            Name = "Data Structures"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Fundamentals of web development",
                            DurationInHours = 50,
                            InstructorId = 2,
                            Name = "Web Development"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Software development principles and practices",
                            DurationInHours = 30,
                            InstructorId = 1,
                            Name = "Software Engineering"
                        });
                });

            modelBuilder.Entity("Student_Management_System.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mohamed@gmail.com",
                            Name = "Mohamed Ahmed",
                            Specialization = "C# Programming"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ahmed@gmail.com",
                            Name = "Ahmed Hassan",
                            Specialization = "Database Systems"
                        },
                        new
                        {
                            Id = 3,
                            Email = "omar@gmail.com",
                            Name = "Omar Ali",
                            Specialization = "Web Development"
                        });
                });

            modelBuilder.Entity("Student_Management_System.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("students", null, t =>
                        {
                            t.HasCheckConstraint("CK_Student_Age", " [Age] >=16");

                            t.HasCheckConstraint("CK_Student_Email", "[Email] LIKE '%@%.%'");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "ahmed@gmail.com",
                            FullName = "Ahmed Ali",
                            Percentage = 85.50m
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Email = "sara@gmail.com",
                            FullName = "Sara Mohamed",
                            Percentage = 91.25m
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Email = "omar@gmail.com",
                            FullName = "Omar Hassan",
                            Percentage = 78.75m
                        },
                        new
                        {
                            Id = 4,
                            Age = 18,
                            Email = "mona@gmail.com",
                            FullName = "Mona Ahmed",
                            Percentage = 88.00m
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            Email = "youssef@gmail.com",
                            FullName = "Youssef Ali",
                            Percentage = 95.50m
                        },
                        new
                        {
                            Id = 6,
                            Age = 20,
                            Email = "nour@gmail.com",
                            FullName = "Nour Khaled",
                            Percentage = 82.25m
                        },
                        new
                        {
                            Id = 7,
                            Age = 19,
                            Email = "hana@gmail.com",
                            FullName = "Hana Samir",
                            Percentage = 90.00m
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            Email = "mahmoud@gmail.com",
                            FullName = "Mahmoud Adel",
                            Percentage = 76.50m
                        },
                        new
                        {
                            Id = 9,
                            Age = 18,
                            Email = "laila@gmail.com",
                            FullName = "Laila Hassan",
                            Percentage = 93.75m
                        },
                        new
                        {
                            Id = 10,
                            Age = 21,
                            Email = "khaled@gmail.com",
                            FullName = "Khaled Mostafa",
                            Percentage = 87.50m
                        });
                });

            modelBuilder.Entity("CourseStudent", b =>
                {
                    b.HasOne("Student_Management_System.Course", null)
                        .WithMany()
                        .HasForeignKey("CoursesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Student_Management_System.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Student_Management_System.Course", b =>
                {
                    b.HasOne("Student_Management_System.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("Student_Management_System.Instructor", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
